### PR TITLE
shove fast

### PR DESCRIPTION
**Pull request by nalinbhardwaj**

### CODE REVIEW

**Review by dcposch — APPROVED** [review]
🚀

**Comment by dcposch** [comment]
## Follow-up request / shovel logs

```
p=1 v=436c chain=84532 src=base-sepolia dst=transfers n=5918582 h= nrows=12 delta=1 elapsed=17.801278ms msg=converge
```

would love to get a something like this

```
p=1 v=436c chain=84532 src=base-sepolia dst=transfers n=5918582 h= nrows=12 delta=1 napi=1 elapsed=17ms msg=converge
```
- ensure `nrows` wrote to pg successfully (or if async, print error after short timeout if they dont)
- **show num node api calls.** this'll show whether we're doing an n+1 query (loading block bodies vs just headers), good sanity check

**Comment by ryandotsmith** [comment]
> ## Follow-up request / api req counts in shovel logs

Great suggestion. Will do.

**Comment by dcposch** [comment]
## One more idea

> **BEHIND 550 BLOCKS ETA=7min p=1 v=436c chain=84532 src=base-sepolia dst=transfers tip=5918582 nblocks=100 nrows=272 napi=1 elapsed=500ms 

vs

> **READY p=1 v=436c chain=84532 src=base-sepolia dst=transfers tip=5918582 nblocks=1 nrows=18 napi=1 elapsed=50ms 

> **READY p=1 v=436c chain=84532 src=base-sepolia dst=transfers tip=5918582 nblocks=8  NREORG=7 nrows=18 napi=1 elapsed=50ms

- status upfront
- bonus points for reorg display
- & just to confirm: this line prints *after* nrows were successfully written to pg, right?

**Comment by ryandotsmith** [comment]
> - & just to confirm: this line prints *after* nrows were successfully written to pg, right?

Correct

**Pull request merged**
