### PR TITLE
web: i18n, translate to Spanish

### PR DESCRIPTION
**Pull request by Ethanol48**
i18n functionality has been tested and it works, there's some minor testing left.

all the "sublinks" haven't been tested if they work properly, and I need to verify that the spanish translations are well integrated with the context.

### CODE REVIEW

**Comment by Ethanol48** [comment]
I noticed a component that queries the main `README.md` of the repo, because of i18n this cannot be used, I refactored the code and exported the FAQ to i18n files.

**Comment by Ethanol48** [comment]
In the last commit I moved the i18n provider to `layout.tsx`.

**Comment by dcposch** [comment]
## Screenshots

image

image

image
image



image
image
image

**Review by dcposch — APPROVED** [review]
🚀

**Pull request merged**
