### PR TITLE
`npm install` improvements

### PR DESCRIPTION
**Pull request by antonok-edm**
`npm install` doesn't automatically run `build` scripts, but it [does](https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-install) run `prepare` scripts.

Not sure how you were previously handling this (maybe `eas` has some special handling?), but this change should compile all of the `@daimo/*` packages when running `npm install` in the repo.

I've also updated `@daimo/api` to use the same tsconfig as the other packages (uncovering a type bug in the process!).

### CODE REVIEW

**Review by dcposch — APPROVED** [review]
Looks great, thanks!

**Comment by antonok-edm** [comment]
> Not sure why this caught an extra type issue when `npm test` runs `tsc` already

`validateMemo` is exported, but it returns `MemoStatus`, which wasn't previously exported as a type.

Could be because of `--transpile-only`? I'm not super familiar with how that works.

> I don't think we need the "prepare" script. CI is unhappy now, probably because of that

Super weird, `npm ci` fails on a fresh checkout of this branch, but then running it a second time succeeds :shrug:

I'll try to look into this further later.

**Comment by dcposch** [comment]
Common pattern I've seen with npm is

```
npm i # or npm ci
npm run build
```

& we're doing that before invoking eas, so I think that part's fine?

**Comment by antonok-edm** [comment]
> so I think that part's fine?

What I'm trying to address is that when I'm following [these steps](https://github.com/daimo-eth/daimo/issues/930#issuecomment-2035832619) to build locally and launching the app, there's immediately a runtime error because it tries to import from `dist` folders that don't exist yet (i.e. `tsc` hasn't been run in any of the dependencies).

I did find a [couple](https://earthly.dev/blog/setup-typescript-monorepo/) of [references](https://spin.atomicobject.com/typescript-project-workspaces/) to using the `composite` setting for `tsconfig.json`, which at least builds all of the dependencies recursively with a single `tsc --build` invokation from `apps/daimo-mobile`. Just updated here. Can we give that a try on CI to make sure it doesn't mess with anything else?

**Comment by dcposch** [comment]
Can revisit

**Pull request closed without merging**
