### PR TITLE
fix expo doctor

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
`expo doctor` has been failing on EAS for a while: https://expo.dev/accounts/daimo/projects/daimo/builds/c92a6039-c8eb-44b5-8c5c-769cbc8fe85d

Android builds hadn't been working on my new laptop and some googling suggested running that, and it did indeed fix local builds not working, so this is probably a good change to make.

### CODE REVIEW

**Review by dcposch — COMMENTED** [review]
LGTM, nice cleanup

You could add it to the root project lint, too

Current
```
    "lint": "turbo lint && syncpack list-mismatches",
```

After
```
    "lint": "turbo lint && syncpack list-mismatches && expo-doctor",
```

**Comment by nalinbhardwaj** [comment]
holding off on merging this, it's weird but it seems like (at least on my laptop) `npm run dev` has significantly longer startup time after this commit? kinda wack

**Comment by dcposch** [comment]
This doesn't entirely fix `expo-doctor`

image

image

**Comment by dcposch** [comment]
may be able to supersede with #635

**Comment by dcposch** [comment]
superseded by #635

**Pull request closed without merging**
